import * as cdk from 'aws-cdk-lib';
import * as secretsmanager from 'aws-cdk-lib/aws-secretsmanager';
import { Construct } from 'constructs';

export interface SecretsStackProps extends cdk.StackProps {
  readonly postgresUrl: secretsmanager.Secret;
  // The real value from your Okta app registration (docs/01-prerequisites.md).
  // Passed as a SecretValue, not a plain string, so it never appears in
  // logs or CDK's own diagnostic output. Sourced from CDK context
  // (-c oidcClientSecret=...) in bin/app.ts, the same input channel as
  // oidcIssuer and oidcClientId -- this is a PoC/reference deployment;
  // production use should weigh sourcing this from an existing
  // out-of-band secret instead, since context values are written to
  // cdk.context.json on disk.
  readonly oidcClientSecretValue: cdk.SecretValue;
}

export interface GatewaySecrets {
  readonly jwtSecret: secretsmanager.Secret;
  readonly oidcClientSecret: secretsmanager.Secret;
  readonly postgresUrl: secretsmanager.Secret;
  readonly adminWriteKey: secretsmanager.Secret;
}

/**
 * Every generated secret the gateway and admin console need, except the
 * database connection URL (created in database-stack.ts, since it's
 * derived from the Aurora cluster).
 *
 * The OIDC client secret is the one secret here that ISN'T generated --
 * it's external configuration from your Okta app registration, supplied
 * as a required deploy-time input (see bin/app.ts), the same category as
 * oidcIssuer and oidcClientId. An earlier draft created this secret EMPTY
 * and asked users to populate it manually after deploy -- that was a real
 * bug, not just an inconvenience: the gateway validates its config schema
 * at boot and treats client_secret as required, so it crash-looped on
 * every launch attempt with an empty value, and ECS Express Mode gave up
 * and rolled back the whole stack before a human ever got the chance to
 * run the "populate it after deploy" step. The fix is structural: the real
 * value must exist BEFORE the gateway's ECS service is ever created, which
 * means it has to come in as a real deploy-time parameter, not be
 * generated by CDK and patched in later.
 */
export class SecretsStack extends cdk.Stack {
  public readonly gatewaySecrets: GatewaySecrets;
  public readonly consoleSessionSecret: secretsmanager.Secret;

  constructor(scope: Construct, id: string, props: SecretsStackProps) {
    super(scope, id, props);

    // No explicit secretName: CloudFormation generates a unique physical
    // name per stack (e.g. ClaudeGatewaySecretsStack-GatewayJwtSecret-xxxxx).
    // An earlier draft hardcoded plain names like "gateway-jwt-secret" --
    // that collides if this stack is ever deployed more than once in the
    // same account/region (confirmed the hard way: colliding with an
    // existing manually-created secret of the same name caused a real
    // CREATE_FAILED/rollback during this repo's own fresh-deploy test).
    // The gateway/console only ever reference these secrets by ARN (passed
    // through as CDK props), so the generated name doesn't need to be
    // predictable.
    const jwtSecret = new secretsmanager.Secret(this, 'GatewayJwtSecret', {
      description: 'JWT signing secret for Claude apps gateway sessions',
      generateSecretString: {
        passwordLength: 44, // ~32 bytes of entropy base64-encoded, matching `openssl rand -base64 32`
        excludePunctuation: true,
      },
    });

    // Seeded with the REAL value from the start (see the class doc above
    // for why this changed from an empty placeholder). `secretStringValue`
    // takes a SecretValue token, which CDK keeps out of the synthesized
    // template -- CloudFormation resolves it at deploy time via a
    // dynamic reference, so `cdk synth`'s output never contains the
    // plaintext secret.
    const oidcClientSecret = new secretsmanager.Secret(this, 'GatewayOidcClientSecret', {
      description: 'Okta OIDC client secret for the Claude apps gateway, set to its real value at deploy time -- see docs/01-prerequisites.md and docs/02-deploy.md.',
      secretStringValue: props.oidcClientSecretValue,
    });

    const adminWriteKey = new secretsmanager.Secret(this, 'GatewayAdminWriteKey', {
      description: 'Admin API write key for the Claude apps gateway spend-limits API (out-of-band CLI/automation verification only; the admin console never uses this -- it authenticates as the signed-in admin instead)',
      generateSecretString: {
        passwordLength: 44,
        excludePunctuation: true,
      },
    });

    this.gatewaySecrets = {
      jwtSecret,
      oidcClientSecret,
      postgresUrl: props.postgresUrl,
      adminWriteKey,
    };

    this.consoleSessionSecret = new secretsmanager.Secret(this, 'AdminConsoleSessionSecret', {
      description: 'Session signing key for the Claude gateway admin console',
      generateSecretString: {
        passwordLength: 44,
        excludePunctuation: true,
      },
    });

    // Secret names are CDK/CloudFormation-generated (no explicit
    // secretName -- see above). This ARN is kept as an output purely for
    // operator convenience (e.g. to look up the secret in the console or
    // rotate it later) -- deploy no longer depends on populating it
    // manually after the fact.
    new cdk.CfnOutput(this, 'OidcClientSecretArn', {
      value: oidcClientSecret.secretArn,
      description: "ARN of the gateway's Okta OIDC client secret, set to its real value at deploy time.",
    });
  }
}
